fixtures:
  repositories:
    fstab:   "https://github.com/AlexCline/puppet-fstab.git"
    dirtree: "https://github.com/AlexCline/puppet-dirtree.git"
    stdlib: 
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.1.0"
  symlinks:
    mounts: "#{source_dir}"
